### ISSUE TITLE
Show My Media in navigation menu

### ISSUE THREAD

**Issue by cdipe** [kaltura/moodle_plugin#117]
The My Media link in the navigation menu is hidden under the Site Home link. This has recently become kind of a problem, since Kaltura decided to remove the recording options from within activites/assignments and where the HTML-editor is used.

To launch Capturespace in moodle, the user now need to go via the My Media page. As we at the Linnaeus University see it, this results in a confusing and awkward workflow: When for instance watching a video in a forum and needing to respond with another video, the user have to leave the forum, go to My Media, make recording, fins his way back to the same forum thread and there post/select the video... not very smart.

But in order to make this at least a little bit easier it would benefit the users if the My Media link was visible all the time, please see attached suggestion.

[Suggested improvement regarding My Media in the Moodle menu.docx](https://github.com/kaltura/moodle_plugin/files/325117/Suggested.improvement.regarding.My.Media.in.the.Moodle.menu.docx)

**Comment by kaltura-hooks** [comment]
Hi @cdipe,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa \"kaltura*\"
```

```
For deb based systems:
```

```
    # dpkg -l \"kaltura-*\"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by cdipe** [comment]
Hi, sorry, thought the data was in the attachment.
This affects Moodle 2.0.8.7 and Moodle 3.0+ and Kaltura KAF KMS (moodle) version 5.47.04, build 0
SaaS

**Comment by muli** [comment]
Hello @cdipe, thanks for reporting this issue.

You wrote that it affects Moodle 2.0.8.7, I guess that you meant Moodle 2.8.7?

Regardless, we will look into this issue and will consult with our Product team.

**Comment by cdipe** [comment]
Ah, sorry again - yes, moodle 2.8.7. Thank you!

**Comment by gonenradai** [comment]
@cdipe 
The issue of capturespace removed from within "browse and embed" (the KAF widget opened through the HTML editor for content creation & selection) is known to us and is going to be handled in KAF by bringing back the recording options (probably configurable).

That said, your suggestion may make sense anyway to better expose the my-media feature, regardless of the appearance of the recording tools within the HTML editor video embedding flow.
So I think it would still be something that our product team would like to consider.

**Comment by cdipe** [comment]
@gonenradai 
That sounds great, thank you!

**Comment by muli** [comment]
@cdipe:
We discussed this feature request with our Product team, and it was approved. However, since we're close to releasing our next version (4.0.10), then we'll include this feature in the following version.

Thanks again for your suggestion!

**Comment by cdipe** [comment]
Excellent, thank you!

**Comment by muli** [comment]
Hi @cdipe,

I just wanted to fill you in that our new plugin supports the new "Boost" theme - and now we added the "My Media" link to the "Flat navigation drawer", which will be always visible to users (assuming that they have the permission [or "capability"] to do so).

![my media in navigation drawer](https://user-images.githubusercontent.com/1042806/27168653-579e4f8a-51af-11e7-8fee-48138c903ab6.png)

**Comment by cdipe** [comment]
Thank you.
