### ISSUE TITLE
Atto plugin tooltip is "Kaltura Media", should be "Embed Kaltura Media"?

### ISSUE THREAD

**Issue by alexumn** [kaltura/moodle_plugin#125]
In Moodle's Atto HTML editor, the button to embed media from Kaltura has the tooltip "Kaltura Media". The same button in both Moodle's older TinyMCE plugin, and Canvas' HTML editor, has the tooltip "Embed Kaltura Media". I suggest changing the language string (component: atto_kalturamedia, string: pluginname) accordingly. We'll be doing this as a local customization in advance of the fall term.

For reference, we're using Kaltura v2015120930 in Moodle 3.0. At https://github.com/kaltura/moodle_plugin/blob/a30f0b185f5435c76633ab235bc0aa6927acb9cb/lib/editor/atto/plugins/kalturamedia/lang/en/atto_kalturamedia.php I see this string has not changed in subsequent releases.

**Comment by kaltura-hooks** [comment]
Hi @alexumn,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa \"kaltura*\"
```

```
For deb based systems:
```

```
    # dpkg -l \"kaltura-*\"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by muli** [comment]
Hi @alexumn,

Thanks for reporting this issue. I will pass your suggestion to our product team and will update once we have an answer.
I believe that this change will be welcomed for the sake of consistency across our products.

Thanks again!

**Comment by muli** [comment]
Fixed in https://github.com/kaltura/moodle_plugin/pull/148.
