### ISSUE TITLE
Students can edit assignments after deadline

### ISSUE THREAD

**Issue by amandadoughty** [kaltura/moodle_plugin#128]
One of our Learning Techs has reported the following problem:

I have uncovered a slightly odd behaviour with the Kaltura Video Assignment in Moodle. I tested this in my playspace. Basically, Mediaspace allows a student to access their video assignment submission via their My Media page on Mediaspace, and edit (e.g. trim) replace or delete the file - even after the video assignment deadline has passed. The steps I followed are:
1. Log in with my student id abmx449
2. Go to a video assignment. The settings for the assignment are Prevent Late Submissions: Yes; Allow resubmitting: No
3. Submit a file
4. Wait for the deadline of the assignment to pass
5. Go to http://mediaspace.city.ac.uk/my-media
6. Find your file in the list of media, click Edit
7. Replace the video file with another one
The thumbnail preview in the moodle gradebook does not change, but the new video is played when the lecturer watches it.
This is obviously a problem as it allows for students to modify their submission after the deadline.

**Comment by kaltura-hooks** [comment]
Hi @amandadoughty,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by amandadoughty** [comment]
Kaltura SaaS

**Comment by muli** [comment]
Hi @amandadoughty,

Thank you for contacting us.

In KAF, it is possible to configure Browse and Embed to ask the user, upon clicking "Select" to select the media, whether he wants to have the video submitted as an assignment or not.

When a user clicks "Yes" to submit his media as an assignment, the media is being cloned and the new copy is submitted as the assignment. This copy can not be accessed in any way by the student - preventing him from editing it after submission.

In order to activate this feature, you should access the KAF admin page -> Browse and Embed -> find enableAssignmentSubmission and change this setting to "Yes".

Please let us know if you have further questions or concerns regarding this issue.

Thanks,
Muli.

**Comment by amandadoughty** [comment]
We don’t seem to have a browse and embed module in mediaspace.city.ac.uk/admin/config
![image001](https://cloud.githubusercontent.com/assets/4435897/20523240/ffc58cfa-b0ab-11e6-9fdb-8cd34fd137eb.png)

**Comment by muli** [comment]
Hi @amandadoughty,

If you can't find the "Browseandembed" module in your KAF instance, then you should contact Kaltura Customer Care.

Thank you,
Muli.
