### ISSUE TITLE
Kaltura Video Presentation activity not available to add instance on latest M3.1/3.2 release 4.0.11

### ISSUE THREAD

**Issue by logan-reynolds** [kaltura/moodle_plugin#132]
When I attempt to add course resources on Moodle 3.1.4+ (Build: 20170127) and 3.2.1+ (Build: 20170127) using the corresponding latest 3.1 and 3.2 of Kaltura release 4.0.11 plugins from Moodle.org, Kaltura Video Presentation (kalvidpres) is not available to add on the "Add an activity or resource" screen.  The assignment (kalvidassign) and video resource (kalvidres) activities still appear and can be added/used without any problems, it's only the video presentation that seems to be missing.

**Comment by kaltura-hooks** [comment]
Hi @logan-reynolds,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by gonenradai** [comment]
Hi Logan,

This is intentional.
The video presentation module used a feature which is deprecated in Kaltura due to its dependency on Flash (which is slowly removed from the world).
You can read the official release notes here - https://knowledge.kaltura.com/kaltura-video-package-v4-moodle-release-notes

Instead of using the video presentation resource you should use the Chapters module in KAF which lets you add an entire slide-deck to a video. This supports basically the same use-case on top of the HTML5 player.

There is a migration process that we provide (we run it) to convert all existing video-presentation entries into videos with slides.
Contact your Kaltura rep if you want the migration to be executed on your account.
