### ISSUE TITLE
No video thumbnail in atto and tinymce mymedia pages

### ISSUE THREAD

**Issue by programming2web** [kaltura/moodle_plugin#135]
Hello, 
After texteditor plugin updates from version 2016040530 to 2016122232 we're seeing black boxes instead of video thumbnails in both atto and tinymce my media pages (/lib/editor/tinymce/plugins/kalturamedia/tinymce/ltibrowse.php and /lib/editor/atto/plugins/kalturamedia/ltibrowse_container.php). This happens in Safari, Firefox and Chrome. 

The actual My Media page (/local/mymedia/mymedia.php) works fine. 

This is the javascript error that is spitted on editor mymedia pages:
ReferenceError: kWidget is not defined

**Comment by kaltura-hooks** [comment]
Hi @programming2web,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by muli** [comment]
Hello @programming2web,

Looks like there's an issue with one of the players configured in your KAF admin.
Specifically, in the "Browse and Embed" window, where you choose the video to embed to, we use our player's "thumbnail embed" functionality in order to allow users to preview the video before embedding.

According to the error message you provided, I suspect that KAF is unable to load the player, for some reason.

Can you please go to your KAF admin -> 'Player' tab -> and make sure that the player ID under the 'playerModerationId' is valid? You can also paste it here and we will be glad to help.


Thank you,
Muli.

**Comment by programming2web** [comment]
Hello Muli, 

Yes, that solved the issue. Thank you very much!
