### ISSUE TITLE
4.1 release for Moodle 3.1 kalvidpres does not show up

### ISSUE THREAD

**Issue by rrusso** [kaltura/moodle_plugin#149]
When upgrading all kaltura plugins to 4.1 released today (6/29/2017), we can no longer use the Kaltura Video Presentation module. Even though it has the correct permissions and was installed during the upgrade without incident, the plugin fails to show up in either the add-a-resource dropdown or modal dialogue box.

This problem exists even for the site admin.

I'm looking deeper.

**Comment by kaltura-hooks** [comment]
Hi @rrusso,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by rrusso** [comment]
Let's attack these questions one at a time.

**Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?**
It happens after I install the latest upgrade as Kaltura requires us. It did not happen prior to the upgrade. I've since uninstalled the Moodle kalvidpres mod from Moodle and reinstalled it with no luck fixing the issue. I've not yet been able to track down the root cause.

**Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?**
SaaS so I cannot comment on further questions.

To reproduce my issue, install the latest Kaltura plugins on Moodle 3.1.1. I've done it a few times. It's fun.

**Comment by rrusso** [comment]
It seems this was intentional. Please let your PAYING customers know when deprecating a feature used hundreds of times across many courses in multiple Moodle instances.
