### ISSUE TITLE
kaltura-kaf-uri.com is not owned by kaltura anymore

### ISSUE THREAD

**Issue by rrusso** [kaltura/moodle_plugin#162]
Please give me some advice on how to fix this!

**Comment by gonenradai** [comment]
Hi @rrusso 
Can you explain what the issue is?
That "domain" is simply a placeholder that we put into the rich text editor which is not really loaded by the browser as-is, and should be always getting replaced by the filter plugin with the actual value of kaf_uri that you have configured in your local Kaltura plugin settings.

The fact that it is not a real functional domain shouldn't pose any issue, but if it does - I'd like to understand the actual issue so we can get to the bottom of it and then advise what needs to be done to solve it.

**Comment by rrusso** [comment]
Awesome!
