### ISSUE TITLE
video_title too long

### ISSUE THREAD

**Issue by amandadoughty** [kaltura/moodle_plugin#171]
One of our users is trying to upload a video resource and gets a database error. Debugging shows that this is because the video title for mdl_kalvidres.video_title is more than 100 chars.

The error message is not useful and surely the table should be able to cope with the same number of chars that can be used for the title?

Debug info: Data too long for column 'video_title' at row 1

... SQL

Error code: dmlwriteexception 

    line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
    line 1329 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 1375 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
    line 43 of /mod/kalvidres/lib.php: call to mysqli_native_moodle_database->insert_record()
    line 124 of /course/modlib.php: call to kalvidres_add_instance()
    line 154 of /course/modedit.php: call to add_moduleinfo()

**Comment by muli** [comment]
Hello @amandadoughty,

Ever since our plugin was released, the video_title field was limited to 100 characters. See here: 
https://github.com/kaltura/moodle_plugin/blob/MOODLE_35_STABLE/mod/kalvidres/db/install.xml#L15

I don't really know why this decision was made, but as you can see, we didn't change it as we didn't get any reports from customers having an issue, until now.

I don't see any technical reason not to change this field to allow more characters.

@idodido, can we add this request to the next version's roadmap?

**Comment by idodido** [comment]
hi @amandadoughty 

can you explain the use case? is this a common workflow, or is it just the first time that you encountered it?
as a user, i think that it might be too long for me to read, but i might be mistaken. can you give us some examples?

**Comment by gonenradai** [comment]
From technical perspective - this seems to be a mismatch between the field length in the moodle plugin  and in the Kaltura DB.
While the Kaltura DB schema originally had 60 chars entry name field:
https://github.com/kaltura/server/blame/Naos-14.6.0/alpha/data/sql/schema.sql#L163
Right now, the field as we have it on our SaaS allows up to 256 chars.

we should align the moodle plugin schema to be compatible with the field length we have in the Kaltura DB

**Comment by idodido** [comment]
Thanks @gonenradai 
@muli adding it to the next version roadmap.

**Comment by muli** [comment]
Fixed in v4.1.4 for Moodle 3.4, 3.5 and 3.6.
