### ISSUE TITLE
Add functionality to bulk update media player across all videos

### ISSUE THREAD

**Issue by upats** [kaltura/moodle_plugin#69]
If you change the default player in the KAF or Moodle, previously uploaded videos will retain the old player. The only way to have all of the old videos updated with a new player is to edit a video resource and re-select the video (or delete the old resource and re-add the video new). This is a huge dilemma for us because sometimes an older player will stop working (for many potential reasons) and we need to switch it out ASAP. It's not possible for us to keep track of and manually update every video that's been added to Moodle so there should be some type of bulk update tool available.

It could be a standalone feature that does a find/replace for the playerIDs stored in the embed code in the database with a new playerID. Or maybe the playerID can be stored in a variable that's controlled by the plugin's configuration settings?

We have students trying to convince their professors to upload their videos to youtube instead Kaltura because of this problem... and the professors don't know that their videos aren't working, nor should they ever need to worry about it. Right now it's kind of a mess.

**Comment by kaltura-hooks** [comment]
Hi @upats,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa "kaltura*"
```

```
For deb based systems:
```

```
    # dpkg -l "kaltura-*"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by muli** [comment]
Closing this issue, as it is addressed in the next plugin version.
