### ISSUE TITLE
Plugin for 3.0 not working

### ISSUE THREAD

**Issue by breebee** [kaltura/moodle_plugin#88]
It seems that it keeps giving me a invalid URI... I tried every combination for the server URI as well as in the KAF URI which i understand is for the SaaS account but i tried any way.. Thanks in advance, is it possible that the error is being generated because of moodle being in a sub directory??

**Comment by kaltura-hooks** [comment]
Hi @breebee,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa "kaltura*"
```

```
For deb based systems:
```

```
    # dpkg -l "kaltura-*"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by breebee** [comment]
Ok, i am running moodle 3 fresh install with the kaltura moodle latest release plugin. I am running the free kaltura trial i just signed up for which i believe would be the community edition (said to work with the moodle plugin) which i connect to with https://kmc.kaltura.com/index.php/kmc#admin|users/admin .... I do believe this is a bug, the only thing i did different then any one else was download the version for moodle 3 from the github rather then the 2.9 version available from moodle.

**Comment by muli** [comment]
Hi @breebee,
The Kaltura Moodle Plugin requires a KAF instance. From your description, it sounds like you don't have one. Is that the case?

**Comment by breebee** [comment]
I am assuming this is the case. Do i need to downgrade to 2.9, or the only way is to install kaltura on the server? Sorry for the mistake and thanks for the quick assistance

-OT will youguys be implementing webrtc and throw away the flash?
Here is a gold mine of open source webrtc scripts

https://www.webrtc-experiment.com/

Thakns again you guys are awesome

**Comment by gonenradai** [comment]
@breebee 
Our moodle plugin version 4.x (on moodle.org, and same as you can get here in the stable branch) requires a KAF instance.
If you opened a free trial account on our SaaS - you can get a KAF instance on your account (if you haven't got one).
If you haven't, you can email our support team (they will need your Kaltura Partner ID) and they will create an instance for you.

If you are using the Kaltura CE (i.e. Kaltura server installed on your own server) which I don't think is the case, you should use the Kaltura Moodle plugin v3.1.x

**Comment by breebee** [comment]
Oh thanks! you guys are awesome
